# Url del piso

In [10]:


import requests
from bs4 import BeautifulSoup as bs #Permite extraer el html y analizarlo
import random
import time
import pandas as pd
import numpy as np
from selenium import webdriver #Permite hacer web scrapping
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import undetected_chromedriver as uc #Permite no ser detectado
import time

# Automatizar para todos los pisos

In [61]:
browser = uc.Chrome()

In [62]:
url_grande = 'https://www.idealista.com/areas/alquiler-viviendas/?shape=%28%28sy%7CaFjhxU%7DlIcyDgf%40%7DqNxvAc%60ErxQytHz%7DEpvGi%7E%40%7EzKyzMloN%29%29'

In [64]:
browser.get(url_grande)

In [65]:
browser.find_element("xpath", '//*[@id="didomi-notice-agree-button"]').click()

In [71]:
html = browser.page_source

In [72]:
soup = bs(html, 'html')

In [77]:
#Recoger todos los anuncios
article = soup.find('main',{'class':'listing-items'}).find_all('article')
article

[<article class="item extended-item item-multimedia-container" data-element-id="93913612" data-online-booking="false">
 <picture class="item-multimedia">
 <div class="item-multimedia-pictures">
 <span>1/</span><span>12</span>
 </div>
 <div class="item-ribbon-container">
 </div>
 <div class="item-gallery gallery-height-core-vitals neutral-orientation"><section aria-live="polite" class="image-gallery vertical-scroll-blocked"><div class="image-gallery-content" role="region"><div class="image-gallery-slide-wrapper"><button aria-label="Previous Slide" class="image-gallery-icon image-gallery-left-nav icon-arrow-left" type="button"></button><button aria-label="Next Slide" class="image-gallery-icon image-gallery-right-nav icon-arrow-right" type="button"></button><div class="image-gallery-swipe false" role="list"><div class="image-gallery-slides" role="listitem"><div class="image-gallery-slide center gallery-boost-first" role="img" style="transform: translateX(0%);" tabindex="-1" title="Salón"><figure class="item-gallery"><picture><source srcset="https://img4.idealista.com/blur/WEB_LISTING-M/0/id.pro.es.image.master/5a/a3/7a/874778333.webp" type="image/webp"/><source srcset="https://img4.idealista.com/blur/WEB_LISTING-M/0/id.pro.es.image.master/5a/a3/7a/874778333.jpg" type="image/jpeg"/><img alt="Salón" height="280" src="https://img4.idealista.com/blur/WEB_LISTING-M/0/id.pro.es.image.master/5a/a3/7a/874778333.jpg" width="340"/></picture></figure></div><div class="image-gallery-slide right gallery-boost-next" role="img" style="transform: translateX(100%);" tabindex="-1" title="Salón"><figure class="item-gallery"><picture><source srcset="https://img4.idealista.com/blur/WEB_LISTING-M/0/id.pro.es.image.master/e0/b1/37/874778340.webp" type="image/webp"/><source srcset="https://img4.idealista.com/blur/WEB_LISTING-M/0/id.pro.es.image.master/e0/b1/37/874778340.jpg" type="image/jpeg"/><img alt="Salón" height="280" src="https://img4.idealista.com/blur/WEB_LISTING-M/0/id.pro.es.image.master/e0/b1/37/874778340.jpg" width="340"/></picture></figure></div><div class="image-gallery-slide" role="img" style="transform: translateX(-100%);" tabindex="-1" title="Mapa de la zona"><div class="item-gallery"><div class="map-content"><span class="map-pin hidden green"></span><picture>
 <source srcset="https://st3.idealista.com/static/common/release/modules/resources/img/static-map-placeholder.webp" type="image/webp"/>
 <source srcset="https://st3.idealista.com/static/common/release/modules/resources/img/static-map-placeholder.png" type="image/png"/>
 <img "="" src="https://st3.idealista.com/static/common/release/modules/resources/img/static-map-placeholder.png"/>
 </picture></div></div></div></div></div></div></div></section></div>
 <div class="item-multimedia-shortcuts">
 <button aria-label="Abrir mapa" class="multimedia-shortcut icon-location-outline" data-button-type="MAP"></button>
 </div>
 </picture>
 <div class="item-info-container">
 <a aria-level="2" class="item-link" href="/inmueble/93913612/" role="heading" title="Piso en calle Ruiseñor, 7, Los Pajaritos, Granada">
 Piso en calle Ruiseñor, 7, Los Pajaritos, Granada
 </a>
 <div class="price-row">
 <span class="item-price h2-simulated">775<span class="txt-big">€/mes</span></span>
 </div>
 <div class="item-detail-char">
 <span class="item-detail">2 hab.</span>
 <span class="item-detail">70 m²</span>
 <span class="item-detail">Planta 4ª exterior con ascensor</span>
 <span class="item-detail txt-highlight-red">54 minutos</span>
 </div>
 <div class="item-description description"><p class="ellipsis">
 Piso céntrico recién reformado de 2 dormitorios muy luminoso en calle tranquila. Junto a Juzgados Caleta, Hospitales Virgen de las Nieves y estación de Renfe. Paradas de metro y autobus. Muebles nuevos con armarios empotrados. Aire acondicionado y cierres de aislamiento térmico. Cocina abierta con barra y electrodomést
 </p></div>
 <div class="item-toolbar item-toolbar--with-border">
 <button aria-label="contact phone" class="icon-phone phone-btn hidden-contact-phones_link item-clickable-phone fake-anchor" type="button">
 <span class="hidden-contact-phones_text">Llamar</span>
 <span class="animation_circle">
 <span class="circle"></span>
 <span class="circle"></span>
 <span class="circle"></span>
 </span>
 </button>
 <button aria-label="contact phone" class="icon-phone hidden-contact-phones_link see-phones-btn fake-anchor" type="button">
 <span class="hidden-contact-phones_text">Ver teléfono</span>
 <span class="animation_circle">
 <span class="circle"></span>
 <span class="circle"></span>
 <span class="circle"></span>
 </span>
 </button>
 <button class="trash-btn icon-trash-outline --old action-discard fake-anchor" data-role="add" data-text-remove="Descartar" rel="nofollow" title="Descartar" type="button">
 <span>Descartar</span>
 </button>
 <button class="icon-no-fav --old favorite-btn action-fav fake-anchor" data-role="add" data-text-add="Guardar" data-text-remove="Favorito" title="Guardar" type="button">
 <span>Guardar</span>
 </button>
 </div>
 </div>
 </article>,
 <article class="item extended-item item-multimedia-container" data-element-id="106986388" data-online-booking="false">
 <picture class="item-multimedia">
 <div class="item-multimedia-pictures">
 <span>1/</span><span>10</span>
 </div>
 <div class="item-ribbon-container">
 </div>
 <div class="item-gallery gallery-height-core-vitals neutral-orientation"><section aria-live="polite" class="image-gallery vertical-scroll-blocked"><div class="image-gallery-content" role="region"><div class="image-gallery-slide-wrapper"><button aria-label="Previous Slide" class="image-gallery-icon image-gallery-left-nav icon-arrow-left" type="button"></button><button aria-label="Next Slide" class="image-gallery-icon image-gallery-right-nav icon-arrow-right" type="button"></button><div class="image-gallery-swipe false" role="list"><div class="image-gallery-slides" role="listitem"><div class="image-gallery-slide center" role="img" style="transform: translateX(0%);" tabindex="-1" title="Salón"><figure class="item-gallery"><picture><source srcset="https://img4.idealista.com/blur/WEB_LISTING-M/0/id.pro.es.image.master/2f/9e/f9/1299590675.webp" type="image/webp"/><source srcset="https://img4.idealista.com/blur/WEB_LISTING-M/0/id.pro.es.image.master/2f/9e/f9/1299590675.jpg" type="image/jpeg"/><img alt="Salón" height="280" src="https://img4.idealista.com/blur/WEB_LISTING-M/0/id.pro.es.image.master/2f/9e/f9/1299590675.jpg" width="340"/></picture></figure></div><div class="image-gallery-slide right" role="img" style="transform: translateX(100%);" tabindex="-1" title="Salón"><figure class="item-gallery"><picture><source srcset="https://img4.idealista.com/blur/WEB_LISTING-M/0/id.pro.es.image.master/31/b9/f4/1299590676.webp" type="image/webp"/><source srcset="https://img4.idealista.com/blur/WEB_LISTING-M/0/id.pro.es.image.master/31/b9/f4/1299590676.jpg" type="image/jpeg"/><img alt="Salón" height="280" src="https://img4.idealista.com/blur/WEB_LISTING-M/0/id.pro.es.image.master/31/b9/f4/1299590676.jpg" width="340"/></picture></figure></div><div class="image-gallery-slide" role="img" style="transform: translateX(-100%);" tabindex="-1" title="Mapa de la zona"><div class="item-gallery"><div class="map-content"><div class="no-show-address-feedback"><span class="icon-feedbk-info"></span><span class="no-show-address-feedback-text">Ubicación aproximada.</span></div><picture>
 <source srcset="https://st3.idealista.com/static/common/release/modules/resources/img/static-map-placeholder.webp" type="image/webp"/>
 <source srcset="https://st3.idealista.com/static/common/release/modules/resources/img/static-map-placeholder.png" type="image/png"/>
 <img "="" src="https://st3.idealista.com/static/common/release/modules/resources/img/static-map-placeholder.png"/>
 </picture></div></div></div></div></div></div></div></section></div>
 <div class="item-multimedia-shortcuts">
 <button aria-label="Abrir mapa" class="multimedia-shortcut icon-location-outline" data-button-type="MAP"></button>
 </div>
 </picture>
 <div class="item-info-container">
 <a aria-level="2" class="item-link" href="/inmueble/106986388/" role="heading" title="Piso en calle Castañeda, Carrera de la Virgen - Paseo del Salón, Granada">
 Piso en calle Castañeda, Carrera de la Virgen - Paseo del Salón, Granada
 </a>
 <div class="price-row">
 <span class="item-price h2-simulated">650<span class="txt-big">€/mes</span></span>
 </div>
 <div class="item-detail-char">
 <span class="item-detail">1 hab.</span>
 <span class="item-detail">60 m²</span>
 <span class="item-detail">Planta 3ª interior sin ascensor</span>
 </div>
 <div class="item-description description"><p class="ellipsis">
 PISO DE 1 DORMITORIO - TERCERA PLANTA - SIN ASCENSOR A PARTIR DE FEBRERO - 11 MESES
 ¡Bienvenido a la hermosa ciudad de Granada! Si estás buscando un apartamento para alquilar a partir del 1 de febrero, no busques más, ¡este es el lugar perfecto para ti! Ubicado en el corazón de Granada, en una zona altamente deseable,
 </p></div>
 <div class="listing-tags-container">
 <span class="listing-tags">Alquiler de temporada</span>
 <span class="listing-tags">Apartamento</span>
 </div>
 <div class="item-toolbar item-toolbar--with-border">
 <button class="icon-chat email-btn action-email fake-anchor" type="button"><span>Contactar</span></button>
 <button aria-label="contact phone" class="icon-phone phone-btn hidden-contact-phones_link item-clickable-phone fake-anchor" type="button">
 <span class="hidden-contact-phones_text">Llamar</span>
 <span class="animation_circle">
 <span class="circle"></span>
 <span class="circle"></span>
 <span class="circle"></span>
 </span>
 </button>
 <button aria-label="contact phone" class="icon-phone hidden-contact-phones_link see-phones-btn fake-anchor" type="button">
 <span class="hidden-contact-phones_text">Ver teléfono</span>
 <span class="animation_circle">
 <span class="circle"></span>
 <span class="circle"></span>
 <span class="circle"></span>
 </span>
 </button>
 <button class="trash-btn icon-trash-outline --old action-discard fake-anchor" data-role="add" data-text-remove="Descartar" rel="nofollow" title="Descartar" type="button">
 <span>Descartar</span>
 </button>
 <button class="icon-no-fav --old favorite-btn action-fav fake-anchor" data-role="add" data-text-add="Guardar" data-text-remove="Favorito" title="Guardar" type="button">
 <span>Guardar</span>
 </button>
 </div>
 </div>
 </article>,
 <article class="item extended-item item-multimedia-container" data-element-id="107419800" data-online-booking="false">
 <picture class="item-multimedia">
 <div class="item-multimedia-pictures">
 <span>1/</span><span>31</span>
 </div>
 <div class="item-ribbon-container">
 </div>
 <div class="item-gallery gallery-height-core-vitals neutral-orientation"><section aria-live="polite" class="image-gallery vertical-scroll-blocked"><div class="image-gallery-content" role="region"><div class="image-gallery-slide-wrapper"><button aria-label="Previous Slide" class="image-gallery-icon image-gallery-left-nav icon-arrow-left" type="button"></button><button aria-label="Next Slide" class="image-gallery-icon image-gallery-right-nav icon-arrow-right" type="button"></button><div class="image-gallery-swipe false" role="list"><div class="image-gallery-slides" role="listitem"><div class="image-gallery-slide center" role="img" style="transform: translateX(0%);" tabindex="-1" title="Salón"><figure class="item-gallery"><picture><source srcset="https://img4.idealista.com/blur/WEB_LISTING-M/0/id.pro.es.image.master/67/f6/45/1312191062.webp" type="image/webp"/><source srcset="https://img4.idealista.com/blur/WEB_LISTING-M/0/id.pro.es.image.master/67/f6/45/1312191062.jpg" type="image/jpeg"/><img alt="Salón" height="280" src="https://img4.idealista.com/blur/WEB_LISTING-M/0/id.pro.es.image.master/67/f6/45/1312191062.jpg" width="340"/></picture></figure></div><div class="image-gallery-slide right" role="img" style="transform: translateX(100%);" tabindex="-1" title="Salón"><figure class="item-gallery"><picture><source srcset="https://img4.idealista.com/blur/WEB_LISTING-M/0/id.pro.es.image.master/a5/35/f3/1312191088.webp" type="image/webp"/><source srcset="https://img4.idealista.com/blur/WEB_LISTING-M/0/id.pro.es.image.master/a5/35/f3/1312191088.jpg" type="image/jpeg"/><img alt="Salón" height="280" src="https://img4.idealista.com/blur/WEB_LISTING-M/0/id.pro.es.image.master/a5/35/f3/1312191088.jpg" width="340"/></picture></figure></div><div class="image-gallery-slide" role="img" style="transform: translateX(-100%);" tabindex="-1" title="Mapa de la zona"><div class="item-gallery"><div class="map-content"><span class="map-pin hidden green"></span><picture>
 <source srcset="https://st3.idealista.com/static/common/release/modules/resources/img/static-map-placeholder.webp" type="image/webp"/>
 <source srcset="https://st3.idealista.com/static/common/release/modules/resources/img/static-map-placeholder.png" type="image/png"/>
 <img "="" src="https://st3.idealista.com/static/common/release/modules/resources/img/static-map-placeholder.png"/>
 </picture></div></div></div></div></div></div></div></section></div>
 <div class="item-multimedia-shortcuts">
 <button aria-label="Abrir mapa" class="multimedia-shortcut icon-location-outline" data-button-type="MAP"></button>
 </div>
 </picture>
 <div class="item-info-container">
 <a aria-level="2" class="item-link" href="/inmueble/107419800/" role="heading" title="Piso en calle Periodista Fernando Gómez de la Cruz, 51, Barrio de los Periodistas, Granada">
 Piso en calle Periodista Fernando Gómez de la Cruz, 51, Barrio de los Periodistas, Granada
 </a>
 <div class="price-row">
 <span class="item-price h2-simulated">1.100<span class="txt-big">€/mes</span></span>
 <span class="item-parking">Garaje incluido</span>
 </div>
 <div class="item-detail-char">
 <span class="item-detail">2 hab.</span>
 <span class="item-detail">85 m²</span>
 <span class="item-detail">Planta 1ª exterior con ascensor</span>
 <span class="item-detail txt-highlight-red">1 hora</span>
 </div>
 <div class="item-description description"><p class="ellipsis">
 Elegante piso situado en una inmejorable zona nueva con bares, comercios, zonas verdes, supermercados y situado junto a la E. T. S. de Ingenierías Informática y de Telecomunicación. Excelente comunicación por transporte público y fácil salida a la autovía.
 El piso consta de un amplio salón y 2 dormitorios y cocina. Tod
 </p></div>
 <div class="item-toolbar item-toolbar--with-border">
 <button class="icon-chat email-btn action-email fake-anchor" type="button"><span>Contactar</span></button>
 <button aria-label="contact phone" class="icon-phone phone-btn hidden-contact-phones_link item-clickable-phone fake-anchor" type="button">
 <span class="hidden-contact-phones_text">Llamar</span>
 <span class="animation_circle">
 <span class="circle"></span>
 <span class="circle"></span>
 <span class="circle"></span>
 </span>
 </button>
 <button aria-label="contact phone" class="icon-phone hidden-contact-phones_link see-phones-btn fake-anchor" type="button">
 <span class="hidden-contact-phones_text">Ver teléfono</span>
 <span class="animation_circle">
 <span class="circle"></span>
 <span class="circle"></span>
 <span class="circle"></span>
 </span>
 </button>
 <button class="trash-btn icon-trash-outline --old action-discard fake-anchor" data-role="add" data-text-remove="Descartar" rel="nofollow" title="Descartar" type="button">
 <span>Descartar</span>
 </button>
 <button class="icon-no-fav --old favorite-btn action-fav fake-anchor" data-role="add" data-text-add="Guardar" data-text-remove="Favorito" title="Guardar" type="button">
 <span>Guardar</span>
 </button>
 </div>
 </div>
 </article>,
 <article class="adv noHover">
 <div class="idealista-banner" id="banners_16022">
 <p class="adv_txt"><span>Publicidad</span></p>
 <div class="sas-banner" id="sas_16022"><a href="https://euw1.smartadserver.com/click?imgid=30198416&amp;insid=11503210&amp;pgid=253245&amp;fmtid=16022&amp;ckid=2287330562694929051&amp;uii=3084584584281610953&amp;acd=1740335642102&amp;opid=126bd80b-cc41-4678-bd73-813997b447ce&amp;opdt=1740335642038&amp;tmstp=6654207043&amp;tgt=ope%3dr%3btyp%3dhs%3bauth%3df%3b%3b%24dt%3d1t%3b%24dt%3d1t%3b%24hc&amp;systgt=%24qc%3d1308537863%3b%24ql%3dUnknown%3b%24qpc%3d03503%3b%24qt%3d228_3220_88533t%3b%24dma%3d0%3b%24qo%3d5%3b%24b%3d16999%3b%24o%3d11100%3b%24sw%3d1920%3b%24sh%3d1080&amp;envtype=0&amp;imptype=0&amp;bldv=2657&amp;gdpr=1&amp;gdpr_consent=CQNR_IAQNR_IAAHABBENBdFsAP_gAAAAAAAAHXwBwAIAAqABaAFsAUgC8wHXgAAAFJQAYAAgrWUgAwABBWshABgACCtY6ADAAEFawkAGAAIK1gAA.f_wAAAAAAAAA&amp;pgDomain=https%3a%2f%2fwww.idealista.com%2fareas%2falquiler-viviendas%2f&amp;cappid=2287330562694929051&amp;scriptid=96970&amp;eqs=af47bd52eceb705fc70ad058ffcc2d02dde0547b&amp;go=https%3a%2f%2fbit.ly%2f3qTunhT" target="_blank"><img border="0" height="300" id="img_30198416" src="https://st1.idealista.com/img/inmovilla/23-06/21jun_600x300inmovilla3.gif" width="600"/></a></div>
 <script data-vendor="iab:45" type="text/javascript">
                             var sas = sas || {};
                             sas.cmd = sas.cmd || [];
                             sas.cmd.push(function() {
                                 if(sas.render) {
                                     sas.render('16022');
                                 }
                             });
                         </script><script data-processed="true" data-vendor="iab:45" type="didomi/javascript">
                             var sas = sas || {};
                             sas.cmd = sas.cmd || [];
                             sas.cmd.push(function() {
                                 if(sas.render) {
                                     sas.render('16022');
                                 }
                             });
                         </script>
 </div>
 </article>,
 <article class="item extended-item item-multimedia-container" data-element-id="107184096" data-online-booking="false">
 <picture class="item-multimedia">
 <div class="item-multimedia-pictures">
 <span>1/</span><span>35</span>
 </div>
 <div class="item-ribbon-container">
 </div>
 <div class="item-gallery gallery-height-core-vitals neutral-orientation">
 <div class="mask-wrapper is-clickable">
 <div class="mask" style="touch-action: pan-y; user-select: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); transition-duration: 0s; transform: translateX(0px);">
 <div class="placeholder" style="transform: translateX(-100%);"></div>
 <div class="placeholder" style="transform: translateX(0px);">
 <div class="gallery-fallback icon-no-pics-old picture">
 <picture>
 <source height="280" srcset="https://img4.idealista.com/blur/WEB_LISTING-M/0/id.pro.es.image.master/02/8d/cb/1305486821.webp" type="image/webp" width="340"/>
 <source height="280" srcset="https://img4.idealista.com/blur/WEB_LISTING-M/0/id.pro.es.image.master/02/8d/cb/1305486821.jpg" type="image/jpeg" width="340"/>
 <img alt="Primera foto del inmueble" height="280" loading="lazy" src="https://img4.idealista.com/blur/WEB_LISTING-M/0/id.pro.es.image.master/02/8d/cb/1305486821.jpg" style="visibility: visible;" width="340"/>
 </picture>
 </div>
 </div>
 <div class="placeholder" style="transform: translateX(100%);"></div>
 </div>
 </div>
 </div>
 <div class="item-multimedia-shortcuts">
 <button aria-label="Abrir mapa" class="multimedia-shortcut icon-location-outline" data-button-type="MAP"></button>
 </div>
 </picture>
 <div class="item-info-container">
 <a aria-level="2" class="item-link" href="/inmueble/107184096/" role="heading" title="Piso en camino Gójar, Altos de la Zubia, La Zubia">
 Piso en camino Gójar, Altos de la Zubia, La Zubia
 </a>
 <div class="price-row">
 <span class="item-price h2-simulated">800<span class="txt-big">€/mes</span></span>
 <span class="item-parking">Garaje incluido</span>
 </div>
 <div class="item-detail-char">

In [80]:
#Obtener id de los anuncios (pisos)
id_muebles = [article.get('data-element-id') for article in articles]
id_muebles

['93913612',
 '106986388',
 '107419800',
 None,
 '107184096',
 '107420561',
 '107257812',
 '107420513',
 '107167733',
 '86536865',
 '107289402',
 '107419602',
 '107404064',
 '107419368',
 '31302600',
 '95376382',
 '102815035',
 '97292955',
 '104962835',
 None,
 '105533317',
 '101029576',
 '104893132',
 '40169012',
 '103520256',
 '105558794',
 '103007540',
 '107414989',
 '107414996',
 '107414962',
 '107414303',
 '101645613']

In [82]:
#Eliminar los None
id_muebles = [muebles for muebles in id_muebles if muebles is not None]
id_muebles

['93913612',
 '106986388',
 '107419800',
 '107184096',
 '107420561',
 '107257812',
 '107420513',
 '107167733',
 '86536865',
 '107289402',
 '107419602',
 '107404064',
 '107419368',
 '31302600',
 '95376382',
 '102815035',
 '97292955',
 '104962835',
 '105533317',
 '101029576',
 '104893132',
 '40169012',
 '103520256',
 '105558794',
 '103007540',
 '107414989',
 '107414996',
 '107414962',
 '107414303',
 '101645613']

In [89]:
busqueda = 'shape=%28%28sy%7CaFjhxU%7DlIcyDgf%40%7DqNxvAc%60ErxQytHz%7DEpvGi%7E%40%7EzKyzMloN%29%29'
npagina = 1
ids = []

while True:
    url = f'https://www.idealista.com/areas/alquiler-viviendas/pagina-{npagina}?{busqueda}'
    browser.get(url)

    time.sleep(random.randint(10,12))

    try:
        browser.find_element("xpath", '//*[@id="didomi-notice-agree-button"]').click()
    except:
        pass

    html = browser.page_source
    soup = bs(html, 'html')

    pagina_actual = int(soup.find('div',{'class':'pagination'}).find('li',{'class':'selected'}).text)
    if npagina == pagina_actual:
        articles = soup.find('main',{'class':'listing-items'}).find_all('article')
    else:
        break
    npagina += 1

    for article in articles:
        id_muebles = article.get('data-element-id')

        ids.append(id_muebles)

        time.sleep(random.randint(1,3))
        print(id_muebles)
        ids = [muebles for muebles in ids if muebles is not None]

93913612
106986388
107419800
None
107184096
107420561
107257812
107420513
107167733
86536865
107289402
107419602
107404064
107419368
31302600
95376382
102815035
97292955
104962835
None
105533317
101029576
104893132
40169012
103520256
105558794
103007540
107414989
107414996
107414962
107414303
101645613
107413675
107413705
107413703
None
107413590
107413125
107412549
107412205
107412029
97890561
107411625
99799119
104862787
107411316
95688627
94206633
98514728
106018355
107409362
None
107409125
107408989
97697300
107408173
107407898
107407031
107406781
1984585
100228536
102496071
28688887
101060951
107401239
107400920
104161313
None
104700420
107396267
107396255
105139980
107395759
107395483
107394840
107394578
107394210
107394190
107393742
98836005
107393218
106613722
102033009
None
107390330
107389813
97305923
107387914
107387821
107386473
107384745
38432597
105401520
107376722
97951150
104016587
107374200
107374059
107373295
None
107371029
102277773
103790825
90293309
107349428
106746883
106088380
107373177
107367075
107363927
107365801
104312427
104364703
107378107
105246266
None
107213660
107014436
107374254
105094500
107363686
107312848
107119695
89826331
107211333
106957936
107211382
102745685
101243934
104671353
102745685
None
107195048
107362645
105881572
106408424
106424952
106371109
106740428
107386674
95471146
106325011
107072337
106531711
106906975
106946474
106507480
None
105401198
107333693
101687807
107366440
107366978
107311434
107256806
107384981
107167183
107260135
107291703
107245012
107260615
107291703
104388377
None
107214051
105008779
107381299

KeyboardInterrupt:

In [90]:
ids_casas = pd.DataFrame(ids)
ids_casas.columns = ['id']
ids_casas

            id
0     93913612
1    106986388
2    107419800
3    107184096
4    107420561
..         ...
152  104388377
153  107214051
154  105008779
155  107381299
156  107045262

[157 rows x 1 columns]

In [91]:
#Guardar en un csv los datos
ids_casas.to_csv('ids_casas.csv', index = False)

In [92]:
casas = pd.Series()

In [95]:
def parsear_inmueble(id_inmueble):
    print('\n Casa numero: ' + id_inmueble)
    
    url = "https://www.idealista.com/inmueble/" + id_inmueble + "/"

    browser.get(url)
    html = browser.page_source
    soup = bs(html, 'html')
    
    titulo = soup.find('span',{'class':'main-info__title-main'}).text
    print('\n Titulo: ' + titulo)

    localizacion = soup.find('span', {'class':'main-info__title-minor'}).text
    print('\n Localizacion: ' + localizacion)

    precio = int(soup.find('span',{'class':'txt-bold'}).text.replace('.',''))
    
    c1 = soup.find('div',{'class':'details-property-feature-one'})
    
    caract_basicas = [caract.text.strip() for caract in c1.find_all('li')]
    
    c2 = soup.find('div',{'class':'details-property-feature-two'})
    
    caract_extra = [caract.text.strip() for caract in c2.find_all('li')]

    casas['titulo'] = titulo
    casas['localizacion'] = localizacion
    casas['precio'] = precio
    casas['caracteristicas_basicas'] = caract_basicas
    casas['caracteristicas_extras'] = caract_extra
    df_casas = pd.DataFrame(casas)

    return(df_casas.T)

In [96]:
df_casas = parsear_inmueble(ids_casas.iloc[0].id)
for i in range(1, len(ids)):
    df_casas = pd.concat([df_casas, parsear_inmueble(ids[i])])
    time.sleep(random.randint(4,8))

 Casa numero: 93913612

 Titulo: Alquiler de Piso en calle Ruiseñor, 7

 Localizacion: Los Pajaritos, Granada

 Casa numero: 106986388

 Titulo: Alquiler de Piso en calle Castañeda

 Localizacion: Carrera de la Virgen - Paseo del Salón, Granada

 Casa numero: 107419800

 Titulo: Alquiler de Piso en calle Periodista Fernando Gómez de la Cruz, 51

 Localizacion: Barrio de los Periodistas, Granada

 Casa numero: 107184096

 Titulo: Alquiler de Piso en camino Gójar

 Localizacion: Altos de la Zubia, La Zubia

 Casa numero: 107420561

 Titulo: Alquiler de Piso en Figares

 Localizacion: Granada

 Casa numero: 107257812

 Titulo: Alquiler de Piso en avenida Federico García Lorca

 Localizacion: Barrio de los Periodistas, Granada

 Casa numero: 107420513

 Titulo: Alquiler de Piso en calle Aracena, 27

 Localizacion: Cullar-Vega

 Casa numero: 107167733

 Titulo: Alquiler de Chalet adosado en calle Avellano s/n

 Localizacion: Cajar

 Casa numero: 86536865

 Titulo: Alquiler de Piso en calle Gran Vía de Colón, 46

 Localizacion: Gran Vía, Granada

 Casa numero: 107289402

 Titulo: Alquiler de Ático en Arabial, 16

 Localizacion: Figares, Granada

 Casa numero: 107419602

 Titulo: Alquiler de Piso en calle Periodista José Fernández Martínez, 3

 Localizacion: Barrio de los Periodistas, Granada

 Casa numero: 107404064

 Titulo: Alquiler de Chalet adosado en camino de los Tramposos

 Localizacion: Ogijares

 Casa numero: 107419368

 Titulo: Alquiler de Piso en paseo de Colón, 5

 Localizacion: Albolote

 Casa numero: 31302600

 Titulo: Alquiler de Piso en pasaje profesor sainz cantero, 3

 Localizacion: Gran Capitán, Granada

 Casa numero: 95376382

 Titulo: Alquiler de Casa o chalet independiente en calle Pernaleros Bajo, 17

 Localizacion: San Ildefonso, Granada

 Casa numero: 102815035

 Titulo: Alquiler de Casa o chalet independiente en calle Amapola, 9

 Localizacion: Atarfe

 Casa numero: 97292955

 Titulo: Alquiler de Piso en calle la Palmita, 8

 Localizacion: Barrio de los Periodistas, Granada

 Casa numero: 104962835

 Titulo: Alquiler de Piso en calle Sederos

 Localizacion: Figares, Granada

 Casa numero: 105533317

 Titulo: Alquiler de Piso en calle Gonzalo Gallas s/n

 Localizacion: Ronda - Arabial, Granada

 Casa numero: 101029576

 Titulo: Alquiler de Piso en calle san anton

 Localizacion: Figares, Granada

 Casa numero: 104893132

 Titulo: Alquiler de Piso en calle Doctor Barraquer

 Localizacion: Plaza de Toros, Granada

 Casa numero: 40169012

 Titulo: Alquiler de Piso en calle Bacaque, 2

 Localizacion: Carretera de Granada-La Alcazaba, Alhendin

 Casa numero: 103520256

 Titulo: Alquiler de Piso en Santa Cecilia, 18

 Localizacion: Zona de San Cayetano, Churriana de la Vega

 Casa numero: 105558794

 Titulo: Alquiler de Piso en calle Frascuelo s/n

 Localizacion: Zona Parque de San Roque, Churriana de la Vega

 Casa numero: 103007540

 Titulo: Alquiler de Piso en avenida Profesor Domínguez Ortiz, 4 n

 Localizacion: Barrio de los Periodistas, Granada

 Casa numero: 107414989

 Titulo: Alquiler de Piso en calle Aretusa

 Localizacion: Barrio de los Periodistas, Granada

 Casa numero: 107414996

 Titulo: Alquiler de Piso en calle Aretusa

 Localizacion: Barrio de los Periodistas, Granada

 Casa numero: 107414962

 Titulo: Alquiler de Piso en calle Náyades

 Localizacion: Barrio de los Periodistas, Granada

 Casa numero: 107414303

 Titulo: Alquiler de Ático en calle Andalucía

 Localizacion: Maracena

 Casa numero: 101645613

 Titulo: Alquiler de Ático en Santa Fe

 Localizacion: Área de Granada, Granada

 Casa numero: 107413675

 Titulo: Alquiler de Piso en calle Santa Clotilde, 49 b

 Localizacion: Ronda - Arabial, Granada

 Casa numero: 107413705

 Titulo: Alquiler de Chalet adosado en Barrio de los Periodistas

 Localizacion: Granada

 Casa numero: 107413703

 Titulo: Alquiler de Ático en avenida Doctor Oloriz

 Localizacion: Plaza de Toros, Granada

 Casa numero: 107413590

 Titulo: Alquiler de Piso en Catedral

 Localizacion: Centro, Granada

 Casa numero: 107413125

 Titulo: Alquiler de Piso en calle Real de Cartuja

 Localizacion: San Ildefonso, Granada

 Casa numero: 107412549

 Titulo: Alquiler de Piso en calle Ángel Barrios

 Localizacion: Ronda - Arabial, Granada

 Casa numero: 107412205

 Titulo: Alquiler de Piso en pasaje Algaba

 Localizacion: Casería de Montijo, Granada

 Casa numero: 107412029

 Titulo: Alquiler de Piso en ronda de Alfareros

 Localizacion: Casería de Montijo, Granada

 Casa numero: 97890561

 Titulo: Alquiler de Piso en camino de ronda

 Localizacion: Ronda - Arabial, Granada

 Casa numero: 107411625

 Titulo: Alquiler de Piso en avenida de Madrid, 18

 Localizacion: San Ildefonso, Granada

 Casa numero: 99799119

 Titulo: Alquiler de Piso en calle Doctor Sánchez Mariscal

 Localizacion: Plaza de Toros, Granada

 Casa numero: 104862787

 Titulo: Alquiler de Piso en Ronda - Arabial

 Localizacion: Ronda - Arabial, Granada

 Casa numero: 107411316

 Titulo: Alquiler de Piso en Gran Capitán

 Localizacion: Centro, Granada

 Casa numero: 95688627

 Titulo: Alquiler de Piso en Ronda - Arabial

 Localizacion: Ronda - Arabial, Granada

 Casa numero: 94206633

 Titulo: Alquiler de Piso en calle Pedro Antonio de Alarcón

 Localizacion: Gran Capitán, Granada

 Casa numero: 98514728

 Titulo: Alquiler de Ático en Doctor Fidel Fernandez

 Localizacion: Plaza de Toros, Granada

 Casa numero: 106018355

 Titulo: Alquiler de Piso en avenida de Pulianas

 Localizacion: San Francisco Javier, Granada

 Casa numero: 107409362

 Titulo: Alquiler de Piso en calle Torre de la Cautiva

 Localizacion: Cervantes-Palacio de Deportes, Granada

 Casa numero: 107409125

 Titulo: Alquiler de Piso en calle Rosa Chacel, 4

 Localizacion: Parque Nueva Granada, Granada

 Casa numero: 107408989

 Titulo: Alquiler de Piso en calle Rosa Chacel, 4

 Localizacion: Parque Nueva Granada, Granada

 Casa numero: 97697300

 Titulo: Alquiler de Piso en tiña

 Localizacion: Albaicín, Granada

 Casa numero: 107408173

 Titulo: Alquiler de Piso en calle Rosa Chacel, 4

 Localizacion: Parque Nueva Granada, Granada

 Casa numero: 107407898

 Titulo: Alquiler de Piso en calle Cisne

 Localizacion: Los Pajaritos, Granada

 Casa numero: 107407031

 Titulo: Alquiler de Piso en Albaicín

 Localizacion: Granada

 Casa numero: 107406781

 Titulo: Alquiler de Piso en Arabial s/n

 Localizacion: Ronda - Arabial, Granada

 Casa numero: 1984585

 Titulo: Alquiler de Ático en avenida del Conocimiento, 1

 Localizacion: Campus de la Salud, Granada

 Casa numero: 100228536

 Titulo: Alquiler de Piso en Campus de la Salud

 Localizacion: Granada

 Casa numero: 102496071

 Titulo: Alquiler de Estudio en Recogidas

 Localizacion: Centro, Granada

 Casa numero: 28688887

 Titulo: Alquiler de Piso en calle San Juan de Dios, 12

 Localizacion: Gran Capitán, Granada

 Casa numero: 101060951

 Titulo: Alquiler de Piso en Carrera de la Virgen - Paseo del Salón

 Localizacion: Realejo, Granada

 Casa numero: 107401239

 Titulo: Alquiler de Piso en calle Ángel Barrios

 Localizacion: Ronda - Arabial, Granada

 Casa numero: 107400920

 Titulo: Alquiler de Piso en Ctra Sierra - Acceso Nuevo Alhambra

 Localizacion: Granada

 Casa numero: 104161313

 Titulo: Alquiler de Piso en camino de Ronda, 81

 Localizacion: Ronda - Arabial, Granada

 Casa numero: 104700420

 Titulo: Alquiler de Piso en camino de Ronda

 Localizacion: Ronda - Arabial, Granada

 Casa numero: 107396267

 Titulo: Alquiler de Casa o chalet en Ronda - Arabial

 Localizacion: Ronda - Arabial, Granada

 Casa numero: 107396255

 Titulo: Alquiler de Piso en Gran Capitán

 Localizacion: Centro, Granada

 Casa numero: 105139980

 Titulo: Alquiler de Piso en Ronda - Arabial

 Localizacion: Ronda - Arabial, Granada

 Casa numero: 107395759

 Titulo: Alquiler de Piso en avenida de Dílar

 Localizacion: Zaidín, Granada

 Casa numero: 107395483

 Titulo: Alquiler de Estudio en cuesta de Rodrigo del Campo

 Localizacion: Molinos - Santiago, Granada

 Casa numero: 107394840

 Titulo: Alquiler de Piso en camino de Ronda

 Localizacion: Ronda - Arabial, Granada

 Casa numero: 107394578

 Titulo: Alquiler de Estudio en calle Honda del Realejo

 Localizacion: Molinos - Santiago, Granada

 Casa numero: 107394210

 Titulo: Alquiler de Piso en avenida de la Ilustración, 57

 Localizacion: Campus de la Salud, Granada

 Casa numero: 107394190

 Titulo: Alquiler de Piso en calle Carreterías

 Localizacion: Maracena

 Casa numero: 107393742

 Titulo: Alquiler de Piso en calle Cañaveral

 Localizacion: Ronda - Arabial, Granada

 Casa numero: 98836005

 Titulo: Alquiler de Piso en Plaza de Toros

 Localizacion: Los Pajaritos - Plaza de Toros, Granada

 Casa numero: 107393218

 Titulo: Alquiler de Piso en Plaza de Toros

 Localizacion: Los Pajaritos - Plaza de Toros, Granada

 Casa numero: 106613722

 Titulo: Alquiler de Piso en Placeta de las Escuelas

 Localizacion: Albaicín, Granada

 Casa numero: 102033009

 Titulo: Alquiler de Chalet adosado en paseo de la Ermita

 Localizacion: Zona Parque de la Ermita, Churriana de la Vega

 Casa numero: 107390330

 Titulo: Alquiler de Casa o chalet independiente en Cajar

 Localizacion: Área de Granada, Granada

 Casa numero: 107389813

 Titulo: Alquiler de Piso en calle Alejandro Dumas

 Localizacion: Polígono Cartuja, Granada

 Casa numero: 97305923

 Titulo: Alquiler de Piso en calle Santa Teresa

 Localizacion: Recogidas, Granada

 Casa numero: 107387914

 Titulo: Alquiler de Piso en calle Santa Clotilde, 47

 Localizacion: Ronda - Arabial, Granada

 Casa numero: 107387821

 Titulo: Alquiler de Piso en calle Maestro Vives

 Localizacion: Figares, Granada

 Casa numero: 107386473

 Titulo: Alquiler de Piso en calle Doctor Marañón

 Localizacion: Plaza de Toros, Granada

 Casa numero: 107384745

 Titulo: Alquiler de Piso en Figares

 Localizacion: Granada

 Casa numero: 38432597

 Titulo: Alquiler de Chalet pareado en calle Chipre

 Localizacion: Belicena

 Casa numero: 105401520

 Titulo: Alquiler de Piso en calle Hortensia

 Localizacion: Santa Fe

 Casa numero: 107376722

 Titulo: Alquiler de Piso en calle Cristo de la Yedra, 19

 Localizacion: San Ildefonso, Granada

KeyboardInterrupt:

In [ ]:
df_casas

,titulo,localizacion,precio,caracteristicas_basicas,caracteristicas_extras
0,Alquiler de Piso en calle Castañeda,"Carrera de la Virgen - Paseo del Salón, Granada",650,"[60 m² construidos, 1 habitación, 1 baño, Segu...","[Consumo: \n999 kWh/m² año, Emisiones: \n999 k..."
0,Alquiler de Piso en calle Castañeda,"Carrera de la Virgen - Paseo del Salón, Granada",650,"[60 m² construidos, 1 habitación, 1 baño, Segu...","[Consumo: \n999 kWh/m² año, Emisiones: \n999 k..."
0,Alquiler de Piso en calle Periodista Fernando ...,"Barrio de los Periodistas, Granada",1100,"[85 m² construidos, 81 m² útiles, 2 habitacion...","[Aire acondicionado, Piscina, Zonas verdes, En..."
0,Alquiler de Piso en camino Gójar,"Altos de la Zubia, La Zubia",800,"[90 m² construidos, 3 habitaciones, 2 baños, T...",[Consumo: \n999 kWh/m² año]
0,Alquiler de Piso en Figares,Granada,950,"[100 m² construidos, 90 m² útiles, 3 habitacio...",[En trámite]
...,...,...,...,...,...
0,Alquiler de Piso en calle Doctor Marañón,"Plaza de Toros, Granada",900,"[90 m² construidos, 89 m² útiles, 3 habitacion...","[Aire acondicionado, En trámite]"
0,Alquiler de Piso en Figares,Granada,990,"[134 m² construidos, 92 m² útiles, 3 habitacio...",[No indicado]
0,Alquiler de Chalet pareado en calle Chipre,Belicena,900,"[Chalet pareado, 3 plantas, 250 m² construidos...","[Jardín, Consumo:, Emisiones:]"
0,Alquiler de Piso en calle Hortensia,Santa Fe,780,"[100 m² construidos, 3 habitaciones, 2 baños, ...","[Aire acondicionado, Consumo:, Emisiones:]"
0,"Alquiler de Piso en calle Cristo de la Yedra, 19","San Ildefonso, Granada",850,"[90 m² construidos, 3 habitaciones, 2 baños, T...",[En trámite]

In [98]:
df_casas.reset_index(drop=True, inplace=True)

In [99]:
df_casas

,titulo,localizacion,precio,caracteristicas_basicas,caracteristicas_extras
0,Alquiler de Piso en calle Castañeda,"Carrera de la Virgen - Paseo del Salón, Granada",650,"[60 m² construidos, 1 habitación, 1 baño, Segu...","[Consumo: \n999 kWh/m² año, Emisiones: \n999 k..."
1,Alquiler de Piso en calle Castañeda,"Carrera de la Virgen - Paseo del Salón, Granada",650,"[60 m² construidos, 1 habitación, 1 baño, Segu...","[Consumo: \n999 kWh/m² año, Emisiones: \n999 k..."
2,Alquiler de Piso en calle Periodista Fernando ...,"Barrio de los Periodistas, Granada",1100,"[85 m² construidos, 81 m² útiles, 2 habitacion...","[Aire acondicionado, Piscina, Zonas verdes, En..."
3,Alquiler de Piso en camino Gójar,"Altos de la Zubia, La Zubia",800,"[90 m² construidos, 3 habitaciones, 2 baños, T...",[Consumo: \n999 kWh/m² año]
4,Alquiler de Piso en Figares,Granada,950,"[100 m² construidos, 90 m² útiles, 3 habitacio...",[En trámite]
...,...,...,...,...,...
83,Alquiler de Piso en calle Doctor Marañón,"Plaza de Toros, Granada",900,"[90 m² construidos, 89 m² útiles, 3 habitacion...","[Aire acondicionado, En trámite]"
84,Alquiler de Piso en Figares,Granada,990,"[134 m² construidos, 92 m² útiles, 3 habitacio...",[No indicado]
85,Alquiler de Chalet pareado en calle Chipre,Belicena,900,"[Chalet pareado, 3 plantas, 250 m² construidos...","[Jardín, Consumo:, Emisiones:]"
86,Alquiler de Piso en calle Hortensia,Santa Fe,780,"[100 m² construidos, 3 habitaciones, 2 baños, ...","[Aire acondicionado, Consumo:, Emisiones:]"
87,"Alquiler de Piso en calle Cristo de la Yedra, 19","San Ildefonso, Granada",850,"[90 m² construidos, 3 habitaciones, 2 baños, T...",[En trámite]

In [103]:
df_casas.to_csv('casas_idealista.csv', index = False, sep = ';', encoding = 'utf-16')